<h1> HAPPY HOLIDAYS EVERYONE !!   </h1>
<h1> WE HAVE SUCCESFULLY MADE IT GUYS .DEVOPS PIPELINE IS COMPLETE!!!!!! </h1>
<h1> IF YOU ARE READING THIS MESSAGE, KUDDOS TO YOU. YOU DESERVE IT, FOR ALL THE HARDWORK YOU PUT IN.</h1>

<h1> PLEASE EVERYONE,GET OUT AND VOTE. TODAY IS ELECTION DAY, AND THE WILL OF GOD MUST COME TO PASS IN AMERICA !!!!!! </h1>



